### ISSUE TITLE
Publish to pypi?

### ISSUE THREAD

**Issue by Rob-Johnson** [Yelp/pysensu-yelp#8]
Hi,

Is there any reason we're not publishing this to pypi? If not, can we?

**Comment by solarkennedy** [comment]
Nope, no particular reason.
Looking around on pypi.python.org, it looks like we don't have some "yelp" account and it is just people's personal account.

Feel free to do it, or you can assign to me and I would be happy to take care of it!

**Comment by Rob-Johnson** [comment]
@solarkennedy: ok, this is done https://pypi.python.org/pypi/pysensu-yelp/0.2.2

What's your pip username? I'd like to add you as owner to the repo.

**Comment by solarkennedy** [comment]
solarkennedy

**Comment by Rob-Johnson** [comment]
ok, done.
